### ISSUE TITLE
[BE] Add Remix dataset's cellxgene link in API response

### ISSUE THREAD

**Issue by tihuan** [chanzuckerberg/corpora-data-portal#532]
What:
We want DP website to provide a Remix dataset's corresponding cellxgene link. E.g., cellxgene.cziscience.com/e/{file_name}.cxg

How:
1. We need `/project/{id}` to include the Remix dataset cellxgene link
2. Update `corpora-api.yml` accordingly

**Comment by tihuan** [comment]
@Bento007 currently dataasset's schema looks like:

```
dataset_asset:
      type: object
      properties:
        id:
          type: string
        format:
          type: string
          enum: [H5AD, RDS, LOOM, CXG]
        file_name:
          type: string
        type:
          type: string
          enum: [REMIX, ORIGINAL]
        s3_uri:
          type: string
```

Do we just add the following as sibling to `s3_url`?:

```
cellxgene_link:
  type: string
```

Thank you!
